In [3]:
import seaborn as sns
import pandas as pd

In [4]:
df = pd.DataFrame(columns=['model', "accuracy", ])
a = ["logistic regression", 0.66]
b = ["Gradient Boost Decision Tree", 0.73]
c = ["neural network", 0.87]
df.loc[0]=a
df.loc[1]=b
df.loc[2]=c

In [6]:
df

                          model  accuracy
0           logistic regression      0.66
1  Gradient Boost Decision Tree      0.73
2                neural network      0.87

In [12]:
result = pd.read_csv("test_results.csv")
result

    Unnamed: 0  True formation energy  Predicted formation energy
0            1              -2.569766                   -2.104152
1            2              -2.309024                   -2.025519
2            3              -2.016497                   -2.013461
3            4              -1.813126                   -1.991024
4            5              -2.123285                   -2.029601
..         ...                    ...                         ...
74          75              -1.795671                   -1.986427
75          76              -1.674354                   -1.975851
76          77              -2.106002                   -2.030724
77          78              -2.401124                   -2.045950
78          79              -2.455685                   -2.098406

[79 rows x 3 columns]

In [17]:
error_list = []
for i in range(79):
    truevalue = result.loc[i, 'True formation energy']
    predictedvalue = result.loc[i, 'Predicted formation energy']
    error = truevalue - predictedvalue
    error_list.append(error)
result['MAE'] = error_list

In [18]:
result

    Unnamed: 0  True formation energy  Predicted formation energy       MAE
0            1              -2.569766                   -2.104152 -0.465613
1            2              -2.309024                   -2.025519 -0.283505
2            3              -2.016497                   -2.013461 -0.003037
3            4              -1.813126                   -1.991024  0.177898
4            5              -2.123285                   -2.029601 -0.093683
..         ...                    ...                         ...       ...
74          75              -1.795671                   -1.986427  0.190756
75          76              -1.674354                   -1.975851  0.301497
76          77              -2.106002                   -2.030724 -0.075277
77          78              -2.401124                   -2.045950 -0.355174
78          79              -2.455685                   -2.098406 -0.357279

[79 rows x 4 columns]

In [10]:
from figrecipes import PlotlyFig

In [19]:
pf = PlotlyFig(result, y_title="predicted formation energy(eV/atom)", x_title="True formation energy(eV/atom)", filename="GNN regression")
pf.xy(('Predicted formation energy', 'True formation energy'), colors='MAE', colorscale="Picnic")